### PR TITLE
Upgrade to Play2.5-RC1 and avoid future.sequence

### PR DESCRIPTION
**Pull request by mushtaq**

### CODE REVIEW

**Comment by loicdescotte** [comment]
Great addition!  
Could you provide a version without the implicit class? It would be simpler for the tutorial.
Thanks :)

**Comment by mushtaq** [comment]
Done. Thanks.

**Comment by loicdescotte** [comment]
Thanks it's merged!  
I will update the blog now

**Comment by mushtaq** [comment]
Thanks.

**Pull request merged**
